language: node_js

services:
  - couchdb

node_js:
  - "5"

sudo: false

before_script:
  - "npm install add-cors-to-couchdb"
  - "./node_modules/.bin/add-cors-to-couchdb"
  - "npm run jshint"

script: npm test

branches:
  only:
  - master
  - /^greenkeeper/.*$/
